Revert "Revert "arm64: crc32: always assume ARM64_HAS_CRC32""
This causes error in the GCC 12.2.0 compiler as follows:

/root/project/mojito/gcc64/bin/../lib/gcc/aarch64-elf/12.2.0/../../../../aarch64-elf/bin/ld: arch/arm64/lib/crc32.o: in function `crc32_le':
(.text+0x0): undefined reference to `crc32_le_base'
/root/project/mojito/gcc64/bin/../lib/gcc/aarch64-elf/12.2.0/../../../../aarch64-elf/bin/ld: arch/arm64/lib/crc32.o: in function `__crc32c_le':
(.text+0xe0): undefined reference to `__crc32c_le_base'
collect2: error: ld returned 1 exit status

This reverts commit cbd012198d1f9b28cd53b82a3f8d2d9839eabda6.

Signed-off-by: Fiqri Ardyansyah <fiqri0927936@gmail.com>